/**
 * @public
 * A disclosure identifying if the app generated this asset using AI.
 *
 * @remarks
 * Helps users make informed decisions about the content they interact with.
 *
 * AI is generally defined as any machine system that, given an objective, infers how to generate an output from an input.
 * Some examples include "generative AI", "large language models", and "machine learning".
 *
 * **App Generated**
 *
 * 'app_generated' indicates when the app creates or significantly alters an asset using AI. Includes when
 * the app makes a request to a third-party service to do so.
 *
 * A significantly altered asset means the AI changes key information or details, such as
 * removing or replacing key components in the original content, which can include applying style transfer, or changing facial expressions.
 *
 * Label this asset as 'app_generated' under these conditions:
 *
 * The following is true:
 *
 * - The app generates the asset in response to a user's request (including past requests), for example, the asset is not from an asset library.
 *
 * And any of these conditions are also true:
 *
 *  - The AI creates entirely new content from scratch.
 *  - The AI introduces new multimedia, details, or creative elements not originally present.
 *  - The AI removes and replaces the asset's key components.
 *  - The AI alters the asset's appearance, meaning, or context in a way that conveys a different message than the original.
 *
 * **None**
 *
 * 'none' indicates when the asset wasn't generated by the app as a part of any user's specific request, for example, a third-party
 * request, or when the asset wasn't significantly altered by AI.
 */
declare type AiDisclosure = "app_generated" | "none";

declare type AllOrNone<T> = T | Never<T>;

/**
 * @public
 * {@link GetDataTableError} indicating custom error occurred in the app's implementation.
 * This can be used to indicate specific issues that are not covered by other error types.
 */
declare type AppError = {
  /**
   * A custom error occurred in your app.
   *
   * Return this for application-specific errors that don't fit
   * the other categories. Include a descriptive message explaining
   * the error to the user.
   */
  status: "app_error";
  /**
   * Optional message explaining the error.
   */
  message?: string;
};

/**
 * @public
 * {@link InvocationContext} indicating a custom error occurred during data refresh.
 * Triggered when getDataTable returned 'app_error' status.
 * UI should display the error message and help users recover.
 */
declare type AppErrorInvocationContext = {
  /**
   * A custom error occurred during data refresh.
   *
   * This occurs when `getDataTable` returned 'app_error' during a refresh attempt.
   * Your UI should display the error message and help users recover from the specific
   * issue.
   */
  reason: "app_error";
  /**
   * The data source reference that caused the error during refresh.
   */
  dataSourceRef?: DataSourceRef;
  /**
   * The error message to display to the user.
   */
  message?: string;
};

/**
 * @public
 * Cell containing a boolean value.
 *
 * @example Creating a boolean cell
 * ```ts
 * import type { BooleanDataTableCell } from '@canva/intents/data';
 *
 * const isActiveCell: BooleanDataTableCell = {
 *   type: 'boolean',
 *   value: true
 * };
 * ```
 *
 * @example Creating a boolean cell with false value
 * ```ts
 * import type { BooleanDataTableCell } from '@canva/intents/data';
 *
 * const isCompleteCell: BooleanDataTableCell = {
 *   type: 'boolean',
 *   value: false
 * };
 * ```
 *
 * @example Creating an empty boolean cell
 * ```ts
 * import type { BooleanDataTableCell } from '@canva/intents/data';
 *
 * const emptyBooleanCell: BooleanDataTableCell = {
 *   type: 'boolean',
 *   value: undefined
 * };
 * ```
 */
export declare type BooleanDataTableCell = {
  /**
   * Indicates this cell contains a boolean value.
   */
  type: "boolean";
  /**
   * Boolean value (true or false).
   *
   * Use `undefined` for an empty cell.
   */
  value: boolean | undefined;
};

/**
 * @public
 * Configuration for a table column.
 */
export declare type ColumnConfig = {
  /**
   * Name for the column, displayed as header text.
   *
   * If `undefined`, the column will have no header text.
   */
  name: string | undefined;
  /**
   * Expected data type for cells in this column.
   *
   * Use a specific `DataType` for columns with consistent types,
   * or `'variant'` for columns that may contain mixed types.
   */
  type: DataType | "variant";
};

/**
 * @public
 * Main interface for implementing the Data Connector intent.
 *
 * Implementing the Data Connector intent enables apps to import external data into Canva.
 * This allows users to select, preview, and refresh data from external sources.
 */
export declare type DataConnectorIntent = {
  /**
   * Gets structured data from an external source.
   *
   * This action is called in two scenarios:
   *
   * - During data selection to preview data before import (when {@link RenderSelectionUiRequest.updateDataRef} is called).
   * - When refreshing previously imported data (when the user requests an update).
   *
   * @param request - Parameters for the data fetching operation.
   * @returns A promise resolving to either a successful result with data or an error.
   *
   * @example Getting data from an external source
   * ```ts
   * import type { GetDataTableRequest, GetDataTableResponse } from '@canva/intents/data';
   *
   * async function getDataTable(request: GetDataTableRequest): Promise<GetDataTableResponse> {
   *   const { dataSourceRef, limit, signal } = request;
   *
   *   // Check if the operation has been aborted.
   *   if (signal.aborted) {
   *     return { status: 'app_error', message: 'The data fetch operation was cancelled.' };
   *   }
   *
   *   // ... data fetching logic using dataSourceRef, limit, and signal ...
   *
   *   // Placeholder for a successful result.
   *   return {
   *     status: 'completed',
   *     dataTable: { rows: [{ cells: [{ type: 'string', value: 'Fetched data' }] }] }
   *   };
   * }
   * ```
   */
  getDataTable: (request: GetDataTableRequest) => Promise<GetDataTableResponse>;

  /**
   * Renders a user interface for selecting and configuring data from your external sources.
   *
   * @param request - Configuration and callbacks for the data selection UI.
   *
   * @example Rendering a data selection UI
   * ```ts
   * import type { RenderSelectionUiRequest } from '@canva/intents/data';
   *
   * async function renderSelectionUi(request: RenderSelectionUiRequest): Promise<void> {
   *   // UI rendering logic.
   *   // Example: if user selects data 'ref123'.
   *   const selectedRef = { source: 'ref123', title: 'My Selected Table' };
   *   try {
   *     const result = await request.updateDataRef(selectedRef);
   *     if (result.status === 'completed') {
   *       console.log('Selection valid and preview updated.');
   *     } else {
   *       console.error('Selection error:', result.status);
   *     }
   *   } catch (error) {
   *      console.error('An unexpected error occurred during data ref update:', error);
   *   }
   * }
   * ```
   */
  renderSelectionUi: (request: RenderSelectionUiRequest) => void;
};

/**
 * @public
 * {@link InvocationContext} indicating initial data selection flow or edit of existing data.
 */
declare type DataSelectionInvocationContext = {
  /**
   * Initial data selection or editing existing data.
   *
   * This is the standard flow when:
   *
   * - A user is selecting data for the first time
   * - A user is editing a previous selection
   *
   * If `dataSourceRef` is provided, this indicates an edit flow, and you should
   * pre-populate your UI with this selection.
   */
  reason: "data_selection";
  /**
   * If dataSourceRef is provided, this is an edit of existing data flow and UI should be pre-populated.
   */
  dataSourceRef?: DataSourceRef;
};

/**
 * @public
 * Reference to an external data source that can be used to fetch data.
 * Created by Data Connector apps and stored by Canva for data refresh operations.
 *
 * You create this object in your data selection UI and pass it to the
 * `updateDataRef` callback. Canva stores this reference and uses it for
 * future data refresh operations.
 *
 * Maximum size: 5KB
 *
 * @example Defining how to locate external data
 * ```ts
 * const dataSourceRef: DataSourceRef = {
 *   source: JSON.stringify({
 *     reportId: "monthly_sales_001",
 *     filters: { year: 2023, region: "NA" }
 *   }),
 *   title: "Monthly Sales Report (NA, 2023)"
 * };
 * ```
 */
export declare type DataSourceRef = {
  /**
   * Information needed to identify and retrieve data from your source.
   *
   * This string should contain all the information your app needs to
   * fetch the exact data selection later. Typically, this is a serialized
   * object with query parameters, identifiers, or filters.
   *
   * You are responsible for encoding and decoding this value appropriately.
   *
   * Maximum size: 5KB
   */
  source: string;
  /**
   * A human-readable description of the data reference.
   *
   * This title may be displayed to users in the Canva interface to help
   * them identify the data source.
   *
   * Maximum length: 255 characters
   */
  title?: string;
};

/**
 * @public
 * Structured tabular data for import into Canva.
 *
 * This format allows you to provide typed data with proper formatting
 * to ensure it displays correctly in Canva designs.
 *
 * @example Creating a data table
 * ```ts
 * import type { ColumnConfig, DataTableCell, DataTable, DataTableRow } from '@canva/intents/data';
 *
 * const myTable: DataTable = {
 *   columnConfigs: [
 *     { name: 'Name', type: 'string' },
 *     { name: 'Age', type: 'number' },
 *     { name: 'Subscribed', type: 'boolean' },
 *     { name: 'Join Date', type: 'date' }
 *   ],
 *   rows: [
 *     {
 *       cells: [
 *         { type: 'string', value: 'Alice' },
 *         { type: 'number', value: 30 },
 *         { type: 'boolean', value: true },
 *         { type: 'date', value: Math.floor(new Date('2023-01-15').getTime() / 1000) }
 *       ]
 *     },
 *     {
 *       cells: [
 *         { type: 'string', value: 'Bob' },
 *         { type: 'number', value: 24 },
 *         { type: 'boolean', value: false },
 *         { type: 'date', value: Math.floor(new Date('2022-07-20').getTime() / 1000) }
 *       ]
 *     }
 *   ]
 * };
 * ```
 */
export declare type DataTable = {
  /**
   * Column definitions with names and data types.
   *
   * These help Canva interpret and display your data correctly.
   */
  columnConfigs?: ColumnConfig[];
  /**
   * The data rows containing the actual values.
   *
   * Each row contains an array of cells with typed data values.
   */
  rows: DataTableRow[];
};

/**
 * @public
 * Generic type for table cells that resolves to a specific cell type.
 */
export declare type DataTableCell<T extends DataType = DataType> = {
  date: DateDataTableCell;
  string: StringDataTableCell;
  number: NumberDataTableCell;
  boolean: BooleanDataTableCell;
  media: MediaCollectionDataTableCell;
}[T];

/**
 * @public
 * Options for uploading an image asset to the user's private media library.
 */
export declare type DataTableImageUpload = Omit<
  ImageUploadOptions,
  "type" | "parentRef"
> & {
  /**
   * Indicates this value contains options for image uploading.
   */
  type: "image_upload";
};

/**
 * @public
 * Maximum dimensions for imported data tables.
 */
export declare type DataTableLimit = {
  /**
   * The maximum number of rows allowed.
   *
   * Your app should ensure data does not exceed this limit.
   */
  row: number;
  /**
   * The maximum number of columns allowed.
   *
   * Your app should ensure data does not exceed this limit.
   */
  column: number;
};

/**
 * @public
 * Metadata providing additional context about the imported data.
 */
export declare type DataTableMetadata = {
  /**
   * A human-readable description of the dataset.
   *
   * This description helps users understand what data they are importing.
   */
  description?: string;
  /**
   * Information about the data provider or source.
   */
  providerInfo?: {
    /**
     * Name of the data provider.
     */
    name: string;
    /**
     * URL to the provider's website or related resource.
     */
    url?: string;
  };
};

/**
 * @public
 * A row in the data table.
 *
 * @example Creating a single row of data cells
 * ```ts
 * import type { DataTableCell, DataTableRow } from '@canva/intents/data';
 *
 * const row: DataTableRow = {
 *   cells: [
 *     { type: 'string', value: 'Product Alpha' },
 *     { type: 'number', value: 199.99 },
 *     { type: 'boolean', value: true }
 *   ]
 * };
 * ```
 */
export declare type DataTableRow = {
  /**
   * Array of cells containing the data values.
   *
   * Each cell must have a type that matches the corresponding column definition (if provided).
   */
  cells: DataTableCell<DataType>[];
};

/**
 * @public
 * Options for uploading a video asset to the user's private media library.
 */
export declare type DataTableVideoUpload = Omit<
  VideoUploadOptions,
  "type" | "parentRef"
> & {
  /**
   * Indicates this value contains options for video uploading.
   */
  type: "video_upload";
};

/**
 * @public
 * Data types supported for table cells.
 */
export declare type DataType =
  | "string"
  | "number"
  | "date"
  | "boolean"
  | "media";

/**
 * @public
 * Cell containing a date value.
 *
 * @example Creating a date cell
 * ```ts
 * import type { DateDataTableCell } from '@canva/intents/data';
 *
 * const todayCell: DateDataTableCell = {
 *   type: 'date',
 *   value: Math.floor(Date.now() / 1000) // Unix timestamp in seconds
 * };
 *
 * const emptyDateCell: DateDataTableCell = {
 *   type: 'date',
 *   value: undefined
 * };
 * ```
 */
export declare type DateDataTableCell = {
  /**
   * Indicates this cell contains a date value.
   */
  type: "date";
  /**
   * Unix timestamp in seconds representing the date.
   *
   * Use `undefined` for an empty cell.
   */
  value: number | undefined;
};

/**
 * @public
 * A set of dimensions.
 */
declare type Dimensions = {
  /**
   * A width, in pixels.
   */
  width: number;
  /**
   * A height, in pixels.
   */
  height: number;
};

/**
 * @public
 * Successful result from `getDataTable` action.
 */
export declare type GetDataTableCompleted = {
  /**
   * Indicates the operation completed successfully
   */
  status: "completed";
  /**
   * The fetched data formatted as a data table.
   */
  dataTable: DataTable;
  /**
   * Optional metadata providing additional context about the data.
   */
  metadata?: DataTableMetadata;
};

/**
 * @public
 * Error results that can be returned from `getDataTable` method.
 */
export declare type GetDataTableError =
  | OutdatedSourceRefError
  | RemoteRequestFailedError
  | AppError;

/**
 * @public
 * Parameters for the getDataTable action.
 */
export declare type GetDataTableRequest = {
  /**
   * Reference to the data source to fetch.
   *
   * This contains the information needed to identify and retrieve the specific data
   * that was previously selected by the user.
   *
   * Use this to query your external data service.
   */
  dataSourceRef: DataSourceRef;
  /**
   * Maximum row and column limits for the imported data.
   *
   * Your app must ensure the returned data does not exceed these limits.
   *
   * If the requested data would exceed these limits, either:
   *
   * - Truncate the data to fit within limits, or
   * - Return a 'data_table_limit_exceeded' error
   */
  limit: DataTableLimit;
  /**
   * Standard DOM AbortSignal for cancellation support.
   *
   * Your app should monitor this signal and abort any ongoing operations if it becomes aborted.
   */
  signal: AbortSignal;
};

/**
 * @public
 * Result returned from the `getDataTable` action.
 */
export declare type GetDataTableResponse =
  | GetDataTableCompleted
  | GetDataTableError;

/**
 * @public
 * The MIME type of an image file that's supported by Canva's backend.
 */
declare type ImageMimeType =
  | "image/jpeg"
  | "image/heic"
  | "image/png"
  | "image/svg+xml"
  | "image/webp"
  | "image/tiff";

/**
 * @public
 * A unique identifier that points to an image asset in Canva's backend.
 */
declare type ImageRef = string & {
  __imageRef: never;
};

/**
 * @public
 * Options for uploading an image asset to the user's private media library.
 */
declare type ImageUploadOptions = {
  /**
   * The type of asset.
   */
  type: "image";
  /**
   * The ref of the original asset from which this new asset was derived.
   *
   * @remarks
   * For example, if an app applies an effect to an image, `parentRef` should contain the ref of the original image.
   */
  parentRef?: ImageRef;
  /**
   * The URL of the image file to upload.
   * This can be an external URL or a data URL.
   *
   * @remarks
   * Requirements for external URLs:
   *
   * - Must use HTTPS
   * - Must return a `200` status code
   * - `Content-Type` must match the file's MIME type
   * - Must be publicly accessible (i.e. not a localhost URL)
   * - Must not redirect
   * - Must not contain an IP address
   * - Maximum length: 4096 characters
   * - Must not contain whitespace
   * - Must not contain these characters: `>`, `<`, `{`, `}`, `^`, backticks
   * - Maximum file size: 50MB
   *
   * Requirements for data URLs:
   *
   * - Must include `;base64` for base64-encoded data
   * - Maximum size: 10MB (10 × 1024 × 1024 characters)
   *
   * Requirements for SVGs:
   *
   * - Disallowed elements:
   *    - `a`
   *    - `altglyph`
   *    - `altglyphdef`
   *    - `altglyphitem`
   *    - `animate`
   *    - `animatemotion`
   *    - `animatetransform`
   *    - `cursor`
   *    - `discard`
   *    - `font`
   *    - `font-face`
   *    - `font-face-format`
   *    - `font-face-name`
   *    - `font-face-src`
   *    - `font-face-uri`
   *    - `foreignobject`
   *    - `glyph`
   *    - `glyphref`
   *    - `missing-glyph`
   *    - `mpath`
   *    - `script`
   *    - `set`
   *    - `switch`
   *    - `tref`
   * - Disallowed attributes:
   *    - `crossorigin`
   *    - `lang`
   *    - `media`
   *    - `onload`
   *    - `ping`
   *    - `referrerpolicy`
   *    - `rel`
   *    - `rendering-intent`
   *    - `requiredextensions`
   *    - `requiredfeatures`
   *    - `systemlanguage`
   *    - `tabindex`
   *    - `transform-origin`
   *    - `unicode`
   *    - `vector-effect`
   * - The `href` attribute of an `image` element only supports data URLs for PNG and JPEG images.
   * - The URL in the `href` attribute must not point to a location outside of the SVG.
   * - The `style` attribute must not use the `mix-blend-mode` property.
   */
  url: string;
  /**
   * The MIME type of the image file.
   */
  mimeType: ImageMimeType;
  /**
   * The URL of a thumbnail image to display while the image is queued for upload.
   * This can be an external URL or a data URL.
   *
   * @remarks
   * Requirements for external URLs:
   *
   * - Must use HTTPS
   * - Must support [Cross-Origin Resource Sharing](https://www.canva.dev/docs/apps/cross-origin-resource-sharing/)
   * - Must be a PNG, JPEG, or SVG file
   * - Maximum length: 4096 characters
   *
   * Requirements for data URLs:
   *
   * - Must include `;base64` for base64-encoded data
   * - Maximum size: 10MB (10 × 1024 × 1024 characters)
   */
  thumbnailUrl: string;
  /**
   * A disclosure identifying if the app generated this image using AI
   *
   * @remarks
   * Helps users make informed decisions about the content they interact with.
   * See {@link AiDisclosure} for the full definition.
   *
   * **App Generated**
   *
   * 'app_generated' indicates when the app creates or significantly alters an asset using AI. Includes when
   * the app requests a third-party service to take similar action on an image using AI.
   *
   *  Required for the following cases (this list is not exhaustive):
   *  | Case                                                            | Reason                               |
   *  | --                                                              | --                                   |
   *  | AI generates a new image from scratch                           | Creates new creative content         |
   *  | AI changes the style of the image e.g. makes it cartoon         | Significantly alters the style       |
   *  | AI removes an object and replaces it with new content           | Creates new creative content         |
   *  | AI changes the facial expression of a person in an image        | Can alter content's original meaning |
   *  | AI composites multiple images together                          | Significantly alters context         |
   *  | AI expands an image by generating new content to fill the edges | Creates new creative content         |
   *  | AI replaces background by generating new content                | Creates new creative content         |
   *
   * **None**
   *
   * 'none' indicates when the app doesn't create or significantly alter an asset using AI, or as a part of a request
   * to third-party hosted content.
   *
   * Required for the following cases (this list is not exhaustive):
   *  | Case                                                    | Reason                                    |
   *  | --                                                      | --                                        |
   *  | Asset comes from an asset library                       | Didn't generate the asset itself          |
   *  | AI corrects red eyes                                    | A minor correction                        |
   *  | AI removes background without replacement               | Doesn't change original meaning by itself |
   *  | AI changes the color of an object in an image           | Doesn't change original meaning by itself |
   *  | AI detects image defects and suggests manual fixes      | Didn't change the asset itself            |
   *  | AI adjusts brightness and contrast on an image          | Doesn't change original meaning by itself |
   *  | AI upscales an image                                    | Doesn't change original meaning by itself |
   */
  aiDisclosure: AiDisclosure;
} & AllOrNone<Dimensions>;

/**
 * @public
 * Information explaining why the data selection UI was launched.
 */
export declare type InvocationContext =
  | DataSelectionInvocationContext
  | OutdatedSourceRefInvocationContext
  | AppErrorInvocationContext;

/**
 * @public
 * Cell containing a media collection (images) value.
 *
 * @example Creating a media cell with an image
 * ```ts
 * import type { MediaCollectionDataTableCell } from '@canva/intents/data';
 *
 * const mediaCell: MediaCollectionDataTableCell = {
 *   type: 'media',
 *   value: [{
 *     type: 'image_upload',
 *     url: 'https://www.canva.dev/example-assets/image-import/image.jpg',
 *     mimeType: 'image/jpeg',
 *     thumbnailUrl: 'https://www.canva.dev/example-assets/image-import/thumbnail.jpg',
 *     aiDisclosure: 'none'
 *   }]
 * };
 * ```
 *
 * @example Creating an empty media cell
 * ```ts
 * import type { MediaCollectionDataTableCell } from '@canva/intents/data';
 *
 * const emptyMediaCell: MediaCollectionDataTableCell = {
 *   type: 'media',
 *   value: []
 * };
 * ```
 */
export declare type MediaCollectionDataTableCell = {
  /**
   * Indicates this cell contains a media collection.
   */
  type: "media";
  /**
   * Media collection values.
   *
   * Use empty array for an empty cell.
   */
  value: (DataTableImageUpload | DataTableVideoUpload)[];
};

declare type Never<T> = {
  [key in keyof T]?: never;
};

/**
 * @public
 * Formatting metadata for number cells.
 *
 * @example Formatting as currency
 * ```ts
 * import type { NumberDataTableCell } from '@canva/intents/data';
 *
 * const currencyCell: NumberDataTableCell = {
 *   type: 'number',
 *   value: 1234.57,
 *   metadata: { formatting: '[$$]#,##0.00' }
 * };
 * ```
 *
 * @example Formatting as a percentage
 * ```ts
 * import type { NumberDataTableCell } from '@canva/intents/data';
 *
 * const percentCell: NumberDataTableCell = {
 *   type: 'number',
 *   value: 0.1234,
 *   metadata: { formatting: '0.00%' }
 * };
 * ```
 *
 * @example Applying a thousands separator
 * ```ts
 * import type { NumberDataTableCell } from '@canva/intents/data';
 *
 * const largeNumberCell: NumberDataTableCell = {
 *   type: 'number',
 *   value: 1234567.89234,
 *   metadata: { formatting: '#,##0.00' }
 * };
 * ```
 */
export declare type NumberCellMetadata = {
  /**
   * Formatting pattern using Office Open XML Format.
   *
   * These patterns control how numbers are displayed to users,
   * including currency symbols, decimal places, and separators.
   */
  formatting?: string;
};

/**
 * @public
 * Cell containing a numeric value.
 *
 * @example Creating a number cell
 * ```ts
 * import type { NumberCellMetadata, NumberDataTableCell } from '@canva/intents/data';
 *
 * const priceCell: NumberDataTableCell = {
 *   type: 'number',
 *   value: 29.99,
 *   metadata: { formatting: '[$$]#,##0.00' }
 * };
 *
 * const quantityCell: NumberDataTableCell = {
 *   type: 'number',
 *   value: 150
 * };
 *
 * const emptyNumberCell: NumberDataTableCell = {
 *   type: 'number',
 *   value: undefined
 * };
 * ```
 */
export declare type NumberDataTableCell = {
  /**
   * Indicates this cell contains a number value.
   */
  type: "number";
  /**
   * Numeric value within safe integer range.
   *
   * Valid range: `Number.MIN_SAFE_INTEGER` to `Number.MAX_SAFE_INTEGER`
   *
   * Invalid values:
   *
   * - Infinity or -Infinity
   * - NaN
   * - Negative zero (-0)
   * - Denormalized numbers
   *
   * Use `undefined` for an empty cell.
   */
  value: number | undefined;
  /**
   * Optional formatting information for displaying the number.
   *
   * @example Applying display formatting to a number
   * ```ts
   * import type { NumberCellMetadata } from '@canva/intents/data';
   *
   * const currencyFormatting: NumberCellMetadata = { formatting: '[$USD]#,##0.00' };
   * const percentageFormatting: NumberCellMetadata = { formatting: '0.00%' };
   * ```
   */
  metadata?: NumberCellMetadata;
};

/**
 * @public
 * {@link GetDataTableError} indicating the data source reference is no longer valid.
 * This will trigger a re-selection flow for the user.
 */
declare type OutdatedSourceRefError = {
  /**
   * The data source reference is no longer valid.
   *
   * Return this error when the DataSourceRef cannot be used to retrieve data,
   * for example:
   *
   * - The referenced dataset has been deleted
   * - Access permissions have changed
   * - The structure of the data has fundamentally changed
   *
   * This will trigger a re-selection flow, allowing the user to choose a new
   * data source.
   */
  status: "outdated_source_ref";
};

/**
 * @public
 * {@link InvocationContext} indicating an error occurred because the previously selected data source reference is no longer valid.
 * Triggered when getDataTable returned 'outdated_source_ref' during data refresh.
 * UI should guide the user to reselect or reconfigure their data.
 */
declare type OutdatedSourceRefInvocationContext = {
  /**
   * Previously selected data source reference is no longer valid.
   *
   * This occurs when `getDataTable` returned 'outdated_source_ref' during a
   * refresh attempt. Your UI should guide the user to select a new data source
   * or update their selection.
   *
   * The outdated reference is provided to help you suggest an appropriate replacement.
   */
  reason: "outdated_source_ref";
  /**
   * The outdated data source reference that caused the error during refresh.
   */
  dataSourceRef?: DataSourceRef;
};

/**
 * @public
 *
 * Prepares a {@link DataConnectorIntent|DataConnector Intent}.
 *
 * @example
 * ```tsx
 * import { prepareDataConnector } from "@canva/intents/data";
 *
 * prepareDataConnector({
 *  getDataTable: async (params) => {
 *    // Implement the logic to fetch the data table
 *  },
 *  renderSelectionUi: (params) => {
 *    // Implement the UI for the data table selection
 *  },
 * });
 * ```
 */
export declare const prepareDataConnector: (
  implementation: DataConnectorIntent,
) => void;

/**
 * @public
 * {@link GetDataTableError} indicating failure to fetch data from the external source.
 * Typically due to network issues or API failures.
 */
declare type RemoteRequestFailedError = {
  /**
   * Failed to fetch data from the external source.
   *
   * Return this error for network issues, API failures, or other
   * connectivity problems that prevent data retrieval.
   */
  status: "remote_request_failed";
};

/**
 * @public
 * Parameters for rendering the data selection UI.
 */
export declare type RenderSelectionUiRequest = {
  /**
   * Context information about why the data selection UI is being launched.
   *
   * Use this to adapt your UI for different scenarios:
   *
   * - 'data_selection': Initial data selection or editing existing data
   * - 'outdated_source_ref': Previous reference is no longer valid, guide user to reselect
   * - 'app_error': Custom error occurred, show error message and recovery options
   *
   * When `dataSourceRef` is provided, pre-populate your UI with this selection.
   */
  invocationContext: InvocationContext;
  /**
   * Maximum allowed rows and columns for the imported data.
   *
   * Your UI should inform users of these constraints and prevent or warn about
   * selections that would exceed them. This helps users understand why certain
   * data sets might not be available for selection.
   */
  limit: DataTableLimit;
  /**
   * Callback to preview selected data before finalizing import.
   *
   * Call this function when the user selects data to:
   *
   * 1. Show a preview of the selected data to the user
   * 2. Validate that the selection meets system requirements
   *
   * Calling this function will trigger your `getDataTable` implementation.
   * Wait for the promise to resolve to determine if the selection is valid.
   *
   * @param dataSourceRef - Reference object identifying the selected data
   * @returns Promise resolving to success or an error result
   * @throws Will throw CanvaError('bad_request') if
   *  1. {@link DataSourceRef.source} exceeds 5kb.
   *  2. {@link DataSourceRef.title} exceeds 255 characters.
   *  3. {@link GetDataTableCompleted.dataTable} exceeds {@link DataTableLimit} or contains invalid data.
   */
  updateDataRef: (
    dataSourceRef: DataSourceRef,
  ) => Promise<UpdateDataRefResponse>;
};

/**
 * @public
 * Cell containing a text value.
 *
 * @example Creating a string cell
 * ```ts
 * import type { StringDataTableCell } from '@canva/intents/data';
 *
 * const nameCell: StringDataTableCell = {
 *   type: 'string',
 *   value: 'John Doe'
 * };
 *
 * const emptyStringCell: StringDataTableCell = {
 *   type: 'string',
 *   value: undefined
 * };
 * ```
 */
export declare type StringDataTableCell = {
  /**
   * Indicates this cell contains a string value.
   */
  type: "string";
  /**
   * Text content of the cell.
   *
   * Maximum length: 10,000 characters
   *
   * Use `undefined` for an empty cell.
   */
  value: string | undefined;
};

/**
 * @public
 * Successful result from the {@link RenderSelectionUiRequest.updateDataRef} callback.
 */
declare type UpdateDataRefCompleted = {
  /**
   * The data selection was successful and can be previewed.
   */
  status: "completed";
};

/**
 * @public
 * Result returned from the {@link RenderSelectionUiRequest.updateDataRef} callback.
 * Indicates whether {@link DataSourceRef} update succeeded or failed.
 */
export declare type UpdateDataRefResponse =
  | UpdateDataRefCompleted
  | GetDataTableError;

/**
 * @public
 * The MIME type of a video file that's supported by Canva's backend.
 *
 * @remarks
 * - GIFs are treated as videos, not images.
 * - `"application/json"` is only used for Lottie files.
 */
declare type VideoMimeType =
  | "video/avi"
  | "video/x-msvideo"
  | "image/gif"
  | "video/x-m4v"
  | "video/x-matroska"
  | "video/quicktime"
  | "video/mp4"
  | "video/mpeg"
  | "video/webm"
  | "application/json";

/**
 * @public
 * A unique identifier that points to a video asset in Canva's backend.
 */
declare type VideoRef = string & {
  __videoRef: never;
};

/**
 * @public
 * Options for uploading a video asset to the user's private media library.
 */
declare type VideoUploadOptions = {
  /**
   * The type of asset.
   */
  type: "video";
  /**
   * The ref of the original asset from which this new asset was derived.
   *
   * @remarks
   * For example, if an app applies an effect to a video, `parentRef` should contain the ref of the original video.
   */
  parentRef?: VideoRef;
  /**
   * The URL of the video file to upload.
   *
   * @remarks
   * Requirements:
   *
   * - Must use HTTPS
   * - Must return a `200` status code
   * - `Content-Type` must match the file's MIME type
   * - Must be publicly accessible (i.e. not a localhost URL)
   * - Must not redirect
   * - Must not contain an IP address
   * - Maximum length: 4096 characters
   * - Must not contain whitespace
   * - Must not contain these characters: `>`, `<`, `{`, `}`, `^`, backticks
   * - Maximum file size: 100MB
   */
  url: string;
  /**
   * The MIME type of the video file.
   */
  mimeType: VideoMimeType;
  /**
   * The URL of a thumbnail video to display while the video is queued for upload.
   *
   * @remarks
   * Requirements:
   *
   * - Must use HTTPS
   * - Must support [Cross-Origin Resource Sharing](https://www.canva.dev/docs/apps/cross-origin-resource-sharing/)
   * - Maximum length: 4096 characters
   * - The dimensions of the thumbnail video must match the video's aspect ratio to prevent the thumbnail from appearing squashed or stretched
   * - Must not be an AVI file. Although our APIs support uploading AVI videos, Canva can't preview them because of native support of browsers
   */
  thumbnailVideoUrl?: string;
  /**
   * The URL of a thumbnail image to use as a fallback if `thumbnailVideoUrl` isn't provided.
   * This can be an external URL or a data URL.
   *
   * @remarks
   * Requirements for external URLs:
   *
   * - Must use HTTPS
   * - Must support [Cross-Origin Resource Sharing](https://www.canva.dev/docs/apps/cross-origin-resource-sharing/)
   * - Must be a PNG, JPEG, or SVG file
   * - Maximum length: 4096 characters
   *
   * Requirements for data URLs:
   *
   * - Must include `;base64` for base64-encoded data
   * - Maximum size: 10MB (10 × 1024 × 1024 characters)
   * - The dimensions of the thumbnail must match the video's aspect ratio to prevent the thumbnail from appearing squashed or stretched
   */
  thumbnailImageUrl: string;
  /**
   * A disclosure identifying if the app generated this video using AI.
   *
   * @remarks
   * Helps users make informed decisions about the content they interact with.
   * See {@link AiDisclosure} for the full definition.
   *
   * **App Generated**
   *
   * 'app_generated' indicates when the app creates or significantly alters an asset using AI. Includes when
   * the app requests a third-party service to take similar action on a video using AI.
   *
   *  Required for the following cases (this list is not exhaustive):
   *  | Case                                                             | Reason                               |
   *  | --                                                               | --                                   |
   *  | AI generates a new video from scratch                            | Creates new creative content         |
   *  | AI changes the style of the video e.g. makes it cartoon          | Significantly alters the style       |
   *  | AI adds subtitles that rely on subjective interpretation         | Creates new creative content         |
   *  | AI expands a video by generating new content to fill the edges   | Creates new creative content         |
   *  | AI animates an image                                             | Creates new creative content         |
   *  | AI fixes defects e.g. blur in a video by generating details      | Creates new creative content         |
   *  | AI generates a talking head presenter                            | Creates new creative content         |
   *
   * **None**
   *
   * 'none' indicates when the app doesn't create or significantly alter an asset using AI, or as a part of
   * a request to third-party hosted content.
   *
   * Required for the following cases (this list is not exhaustive):
   *  | Case                                                     | Reason                                    |
   *  | --                                                       | --                                        |
   *  | Asset comes from an asset library                        | Didn't generate the asset itself          |
   *  | AI corrects red eyes                                     | A minor correction                        |
   *  | AI adjusts brightness and contrast on a video            | Doesn't change original meaning by itself |
   *  | AI creates a slow motion effect in a video               | Doesn't change original meaning by itself |
   *  | AI adds AI word-by-word transcribed subtitles to a video | Doesn't change original meaning by itself |
   */
  aiDisclosure: AiDisclosure;
} & AllOrNone<Dimensions>;

export {};
